project: map-to-street-view

default_backend: koa

env_watch:
  - scripts/setup_env.sh
  - requirements.txt
  - requirements.lock
  - requirements-dev.txt
  - pyproject.toml
  - poetry.lock
  - uv.lock
  - environment.yml

# Add snapshot_excludes if you want to skip directories during submissions
snapshot_excludes:
  - blueprints
  - cache
  - ./data
  - past_results
  - results
  - sft/1k
  - sft/11k
  - sft/11k-7k-in-progress
  - .venv
  - deps
  - publications

backends:
  - cluster_name: koa
    default_gres: gpu:nvidia_h200_nvl:1
  - cluster_name: delta
    # default_partition: gpuA100x4-preempt
    default_partition: gpuH200x8
    default_gres: gpu:1