project: map-to-street-view

default_backend: koa

cuda_minor_version: 12.8

default_partition: kill-shared

env_watch:
  - scripts/setup_env.sh
  - requirements.txt
  - requirements.lock
  - requirements-dev.txt
  - pyproject.toml
  - poetry.lock
  - uv.lock
  - environment.yml

# Add snapshot_excludes if you want to skip directories during submissions
snapshot_excludes:
  - blueprints
  - cache
  - data
  - past_results
  - results
  - sft
  - .venv