[project]
name = "map-to-street-view"
version = "0.1.0"
description = "Map to Street View"
readme = "README.md"
requires-python = ">=3.10"

# Core dependencies shared by both Mac (CPU/MPS) and HPC (CUDA)
dependencies = [
    "transformers==4.57.1",
    "huggingface_hub>=0.23.0",
]

[project.optional-dependencies]
# HPC group adds distributed / CUDA-related tools,
# but leaves torch/torchvision/torchaudio to be installed manually
hpc = [
    "deepspeed==0.17.1",
    "torchcodec==0.2",
    "accelerate==1.7.0",
    "pandas",
    "datasets>=2.19.0",
    "Pillow>=9.5.0",
    "tqdm",
]

grpo = [
    "torch==2.8.0",
    "torchvision==0.23.0",
    "torchaudio==2.8.0",
    "vllm>=0.11.0",
    "trl @ https://github.com/huggingface/trl/archive/d250e4b94402e5a8eb8703e87704cfe417b33fd2.zip",
    "wandb>=0.17.0",
    "triton",
    "flash-attn>=2.8.3",
    "setuptools",
    "rich>=13.7.0",
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true


[tool.uv]
package = false
no-build-isolation-package = ["flash-attn"]


[tool.uv.sources]
torch = [
  { index = "pytorch-cu128", extra = "grpo" },
]
torchvision = [
  { index = "pytorch-cu128", extra = "grpo" },
]
torchaudio = [
  { index = "pytorch-cu128", extra = "grpo" },
]
