#!/usr/bin/env bash
set -euo pipefail
set -x

log() {
  printf '[setup_env] %s\n' "$*" >&2
}

# Root of the project snapshot (contains repo/ and run_metadata/)
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Load variables from .env if present so downstream commands inherit them
ENV_FILE="${PROJECT_ROOT}/.env"
if [[ -f "${ENV_FILE}" ]]; then
  # shellcheck disable=SC1090  # dynamic path from repository root
  set -a
  source "${ENV_FILE}"
  set +a
  log "Loaded environment variables from ${ENV_FILE}"
fi

# Shared uv-managed environment (overridable via KOA_SHARED_ENV); lives outside job snapshots
SHARED_ENV_DIR="${KOA_SHARED_ENV:-${PROJECT_ROOT}/../.venv}"
mkdir -p "${SHARED_ENV_DIR}"
ENV_PYTHON="${SHARED_ENV_DIR}/bin/python"

# Add uv to PATH
export PATH="${HOME}/.local/bin:${PATH}"

# Cache location for environment hashes (used to detect changes between runs)
ENV_CACHE_DIR="${SHARED_ENV_DIR}/.koa"
ENV_HASH_CACHE="${ENV_CACHE_DIR}/env_hashes.json"

# Locate the manifest generated by `koa submit` (contains env_hashes.json)
RUN_METADATA_DIR="${KOA_RUN_METADATA_DIR:-}"
if [[ -z "${RUN_METADATA_DIR}" && -n "${KOA_RUN_DIR:-}" ]]; then
  RUN_METADATA_DIR="${KOA_RUN_DIR}/run_metadata"
fi
if [[ -z "${RUN_METADATA_DIR}" && -n "${KOA_ML_RESULTS_ROOT:-}" && -n "${SLURM_JOB_ID:-}" ]]; then
  RUN_METADATA_DIR="${KOA_ML_RESULTS_ROOT}/${SLURM_JOB_ID}/run_metadata"
fi

log "Using container-provided CUDA toolchain; no custom setup required"

# Prefer python3, fall back to python; continue even if neither is available
python_bin=""
if command -v python3 >/dev/null 2>&1; then
  python_bin="$(command -v python3)"
elif command -v python >/dev/null 2>&1; then
  python_bin="$(command -v python)"
fi

if [[ -n "${python_bin}" ]]; then
  log "Found python interpreter at ${python_bin}"
else
  log "No system python found; relying on uv-managed interpreter"
fi

# Determine which extras to install (always include hpc; allow callers to add more)
UV_SYNC_EXTRAS="${UV_SYNC_EXTRAS:-hpc}"
IFS=',' read -r -a _extras <<< "${UV_SYNC_EXTRAS}"
UV_SYNC_EXTRA_ARGS=()
for _extra in "${_extras[@]}"; do
  _trimmed="$(echo "${_extra}" | xargs)"
  if [[ -n "${_trimmed}" ]]; then
    UV_SYNC_EXTRA_ARGS+=(--extra "${_trimmed}")
  fi
done
log "uv sync extras: ${UV_SYNC_EXTRAS}"

# Determine whether we need to rebuild or refresh the shared environment
recreate=0
if [[ ! -x "${ENV_PYTHON}" ]]; then
  recreate=1
fi

ENV_HASH_SOURCE=""
if [[ -n "${RUN_METADATA_DIR}" && -f "${RUN_METADATA_DIR}/env_hashes.json" ]]; then
  ENV_HASH_SOURCE="${RUN_METADATA_DIR}/env_hashes.json"
fi

# Compare the last synced env hashes with the current ones; rebuild if they differ
if [[ "${recreate}" -eq 0 && -n "${ENV_HASH_SOURCE}" ]]; then
  mkdir -p "${ENV_CACHE_DIR}"
  if [[ ! -f "${ENV_HASH_CACHE}" ]] || ! cmp -s "${ENV_HASH_SOURCE}" "${ENV_HASH_CACHE}"; then
    recreate=1
  fi
fi

export UV_PROJECT_ENVIRONMENT="${SHARED_ENV_DIR}"
if [[ "${recreate}" -eq 1 ]]; then
  log "Recreating shared environment at ${SHARED_ENV_DIR}"
  # Ensure uv is available for managing the shared environment
  if ! uv --help >/dev/null 2>&1; then
    curl -LsSf https://astral.sh/uv/install.sh | sh
  fi

  # (Re)create the uv-managed environment and install dependencies from this repo snapshot
  uv venv --clear "${SHARED_ENV_DIR}"
  uv sync "${UV_SYNC_EXTRA_ARGS[@]}"

  if [[ -n "${ENV_HASH_SOURCE}" ]]; then
    mkdir -p "${ENV_CACHE_DIR}"
    cp "${ENV_HASH_SOURCE}" "${ENV_HASH_CACHE}"
  fi
else
  log "Shared environment already up to date; skipping rebuild"
fi
